### PR TITLE
Protocol files corrections

### PR DESCRIPTION
**Pull request by KathrynBaker**
Relates to ISISComputingGroup/IBEX#1170

The init wasn't performing as expected, so removed

### CODE REVIEW

**Comment by FreddieAkeroyd** [comment]
Hi Kathryn, don't commnds like voltsp get OK returned? It would be a good idea to check for the return status in case of an error

**Comment by KathrynBaker** [comment]
Hi Freddie,

Typically in ISIS the equipment is in a state which means they don’t respond automatically to every command, so the OK isn’t returned, giving us errors when things are working normally. Certainly the LabVIEW doesn’t check for an OK being returned, and I didn’t notice the lambda actually returning anything when using hyperterm to test the connections when I was troubleshooting.

Regards,
Kathryn

**Comment by ChrisM-S** [comment]
Just a nugget of experience gained painfully on the Binary ICE Thurlby power supply!

As it’s often possible to send two commands together to serial devices, even silent devices can be prompted to return the value just set as a response (a good practice for validation anyway).  This gives the security of a send/acknowledge protocol as long as the driver writer intentionally always pairs silent set/config  commands with a query (or even just a status request).

The advantage of this, without anything else, is that you can tell that the device really failed if nothing returns, not connected correctly etc.  For the Thurlby I was using, sending set requests too close to each other in time seemed to lock up the PS firmware requiring a hard reset!.  A query following the set in the same command and (separated by a “;” I think) prevented this happening however fast the commands were sent.

Hope this saves someone some time in the future!

Chris

Hi Freddie,

Typically in ISIS the equipment is in a state which means they don’t respond automatically to every command, so the OK isn’t returned, giving us errors when things are working normally. Certainly the LabVIEW doesn’t check for an OK being returned, and I didn’t notice the lambda actually returning anything when using hyperterm to test the connections when I was troubleshooting.

Regards,
Kathryn

**Comment by FreddieAkeroyd** [comment]
I'm not sure I follow "Typically in ISIS the equipment is in a state which means they don’t respond automatically to every command". If it's in this state, might it not process commands properly either? I agree with Chris in that you don't know if a command works if you don't get a reply, and you may try to send commands too quickly too if you are not waiting for one.

**Comment by KathrynBaker** [comment]
The hardware is usually set up to not return commands, where available this is often a firmware setting, there is no response to see. It's been running like this for at least ten years, if we want to change this we will need to communicate with all the teams dealing with devices to make sure they know about this, otherwise hot swaps that don't have automatic answers turned on will error. The settings are read back where possible, which is the check that the command has been sent. Many devices don't even have a response setting.

**Comment by FreddieAkeroyd** [comment]
I've just looked on LARMOR and Rob's settings in globals.txt for SDTEST check for OK on reply for the TDK lambda. As time is short I'll merge the current PR, but it is something we should revisit.

SDTEST_01__SETOUTA1=PC
SDTEST_01__SETOUTB1=0x20
SDTEST_01__SETOUTC1=%f
SDTEST_01__SETIN1=OK

**Comment by KathrynBaker** [comment]
I have added this to my list, so hopefully when I next looking at one I can try this.

Regards,
Kathryn

**Comment by kjwoodsISIS** [comment]
We should add it to the list that @AdrianPotter is compiling:
https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_v2.0.0

**Comment by KathrynBaker** [comment]
Did you mean the changes from the ticket (rather than the pull request), or the specific test?

I don’t know if Rob is planning on using a Genesys, but I won’t be interacting with one for the Muon Front End until we (hopefully given that there are other changes needed for it that aren’t needed for this cycle) have another release. So testing whether or not an “OK” is returned might not be possible for this release.

Regards,
Kathryn

**Pull request merged**
